{"text": "2024-10-11 07:31:29 | INFO    | __main__:stash:131 | run - {'image': '20231121', 'version': '0.10.1.post2', 'role': 'EpicPlayer', 'headless': True}\n", "record": {"elapsed": {"repr": "0:00:01.079359", "seconds": 1.079359}, "exception": null, "extra": {"image": "20231121", "version": "0.10.1.post2", "role": "EpicPlayer", "headless": true}, "file": {"name": "claim.py", "path": "/home/runner/work/Epic-Get/Epic-Get/epic/src/claim.py"}, "function": "stash", "level": {"icon": "‚ÑπÔ∏è", "name": "INFO", "no": 20}, "line": 131, "message": "run", "module": "claim", "name": "__main__", "process": {"id": 3792, "name": "MainProcess"}, "thread": {"id": 140026534710144, "name": "MainThread"}, "time": {"repr": "2024-10-11 07:31:29.440990+08:00", "timestamp": 1728603089.44099}}}
{"text": "2024-10-11 07:31:33 | WARNING    | epic_games.agent:get_order_history:467 | Failed to get order history, cookie may have expired - {}\n", "record": {"elapsed": {"repr": "0:00:04.646351", "seconds": 4.646351}, "exception": null, "extra": {}, "file": {"name": "agent.py", "path": "/home/runner/work/Epic-Get/Epic-Get/epic/src/epic_games/agent.py"}, "function": "get_order_history", "level": {"icon": "‚ö†Ô∏è", "name": "WARNING", "no": 30}, "line": 467, "message": "Failed to get order history, cookie may have expired", "module": "agent", "name": "epic_games.agent", "process": {"id": 3792, "name": "MainProcess"}, "thread": {"id": 140026534710144, "name": "MainThread"}, "time": {"repr": "2024-10-11 07:31:33.007982+08:00", "timestamp": 1728603093.007982}}}
{"text": "2024-10-11 07:31:33 | DEBUG    | __main__:create_tasks:66 | Put task - {'title': 'Outliver: Tribulation', 'url': 'https://store.epicgames.com/en-US/p/outliver-tribulations-679884'}\n", "record": {"elapsed": {"repr": "0:00:05.242335", "seconds": 5.242335}, "exception": null, "extra": {"title": "Outliver: Tribulation", "url": "https://store.epicgames.com/en-US/p/outliver-tribulations-679884"}, "file": {"name": "claim.py", "path": "/home/runner/work/Epic-Get/Epic-Get/epic/src/claim.py"}, "function": "create_tasks", "level": {"icon": "üêû", "name": "DEBUG", "no": 10}, "line": 66, "message": "Put task", "module": "claim", "name": "__main__", "process": {"id": 3792, "name": "MainProcess"}, "thread": {"id": 140026534710144, "name": "MainThread"}, "time": {"repr": "2024-10-11 07:31:33.603966+08:00", "timestamp": 1728603093.603966}}}
{"text": "2024-10-11 07:31:33 | DEBUG    | __main__:create_tasks:66 | Put task - {'title': 'Empyrion - Galactic Survival', 'url': 'https://store.epicgames.com/en-US/p/empyrion-galactic-survival-fbd99f'}\n", "record": {"elapsed": {"repr": "0:00:05.242790", "seconds": 5.24279}, "exception": null, "extra": {"title": "Empyrion - Galactic Survival", "url": "https://store.epicgames.com/en-US/p/empyrion-galactic-survival-fbd99f"}, "file": {"name": "claim.py", "path": "/home/runner/work/Epic-Get/Epic-Get/epic/src/claim.py"}, "function": "create_tasks", "level": {"icon": "üêû", "name": "DEBUG", "no": 10}, "line": 66, "message": "Put task", "module": "claim", "name": "__main__", "process": {"id": 3792, "name": "MainProcess"}, "thread": {"id": 140026534710144, "name": "MainThread"}, "time": {"repr": "2024-10-11 07:31:33.604421+08:00", "timestamp": 1728603093.604421}}}
{"text": "2024-10-11 07:31:38 | INFO    | epic_games.agent:claim_weekly_games:294 | claim_weekly_games - {'action': 'go to store', 'url': 'https://store.epicgames.com/en-US/p/outliver-tribulations-679884'}\n", "record": {"elapsed": {"repr": "0:00:09.845079", "seconds": 9.845079}, "exception": null, "extra": {"action": "go to store", "url": "https://store.epicgames.com/en-US/p/outliver-tribulations-679884"}, "file": {"name": "agent.py", "path": "/home/runner/work/Epic-Get/Epic-Get/epic/src/epic_games/agent.py"}, "function": "claim_weekly_games", "level": {"icon": "‚ÑπÔ∏è", "name": "INFO", "no": 20}, "line": 294, "message": "claim_weekly_games", "module": "agent", "name": "epic_games.agent", "process": {"id": 3792, "name": "MainProcess"}, "thread": {"id": 140026534710144, "name": "MainThread"}, "time": {"repr": "2024-10-11 07:31:38.206710+08:00", "timestamp": 1728603098.20671}}}
{"text": "2024-10-11 07:31:51 | INFO    | epic_games.agent:claim_weekly_games:294 | claim_weekly_games - {'action': 'go to store', 'url': 'https://store.epicgames.com/en-US/p/empyrion-galactic-survival-fbd99f'}\n", "record": {"elapsed": {"repr": "0:00:23.192379", "seconds": 23.192379}, "exception": null, "extra": {"action": "go to store", "url": "https://store.epicgames.com/en-US/p/empyrion-galactic-survival-fbd99f"}, "file": {"name": "agent.py", "path": "/home/runner/work/Epic-Get/Epic-Get/epic/src/epic_games/agent.py"}, "function": "claim_weekly_games", "level": {"icon": "‚ÑπÔ∏è", "name": "INFO", "no": 20}, "line": 294, "message": "claim_weekly_games", "module": "agent", "name": "epic_games.agent", "process": {"id": 3792, "name": "MainProcess"}, "thread": {"id": 140026534710144, "name": "MainThread"}, "time": {"repr": "2024-10-11 07:31:51.554010+08:00", "timestamp": 1728603111.55401}}}
{"text": "2024-10-11 07:32:02 | ERROR    | __main__:run:158 | An error has been caught in function 'run', process 'MainProcess' (3792), thread 'MainThread' (140026534710144): - {}\nTraceback (most recent call last):\n  File \"/home/runner/work/Epic-Get/Epic-Get/epic/src/claim.py\", line 162, in <module>\n    asyncio.run(run())\n  File \"/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/asyncio/runners.py\", line 44, in run\n    return loop.run_until_complete(main)\n  File \"/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/asyncio/base_events.py\", line 636, in run_until_complete\n    self.run_forever()\n  File \"/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/asyncio/base_events.py\", line 603, in run_forever\n    self._run_once()\n  File \"/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/asyncio/base_events.py\", line 1909, in _run_once\n    handle._run()\n  File \"/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/asyncio/events.py\", line 80, in _run\n    self._context.run(self._callback, *self._args)\n> File \"/home/runner/work/Epic-Get/Epic-Get/epic/src/claim.py\", line 158, in run\n    await agent.stash()\n  File \"/home/runner/work/Epic-Get/Epic-Get/epic/src/claim.py\", line 151, in stash\n    await self.claim_epic_games(context)\n  File \"/home/runner/work/Epic-Get/Epic-Get/epic/src/claim.py\", line 122, in claim_epic_games\n    await epic.claim_weekly_games(page, single_promotions)\n  File \"/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/tenacity/asyncio/__init__.py\", line 189, in async_wrapped\n    return await copy(fn, *args, **kwargs)\n  File \"/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/tenacity/asyncio/__init__.py\", line 111, in __call__\n    do = await self.iter(retry_state=retry_state)\n  File \"/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/tenacity/asyncio/__init__.py\", line 153, in iter\n    result = await action(retry_state)\n  File \"/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/tenacity/_utils.py\", line 99, in inner\n    return call(*args, **kwargs)\n  File \"/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/tenacity/__init__.py\", line 398, in <lambda>\n    self._add_action_func(lambda rs: rs.outcome.result())\n  File \"/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/concurrent/futures/_base.py\", line 451, in result\n    return self.__get_result()\n  File \"/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/concurrent/futures/_base.py\", line 403, in __get_result\n    raise self._exception\n  File \"/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/tenacity/asyncio/__init__.py\", line 114, in __call__\n    result = await fn(*args, **kwargs)\n  File \"/home/runner/work/Epic-Get/Epic-Get/epic/src/epic_games/agent.py\", line 310, in claim_weekly_games\n    await expect(cta_btn).to_have_text(\"View In Cart\")\n  File \"/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/playwright/async_api/_generated.py\", line 19164, in to_have_text\n    await self._impl_obj.to_have_text(\n  File \"/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/playwright/_impl/_assertions.py\", line 481, in to_have_text\n    await self._expect_impl(\n  File \"/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/playwright/_impl/_assertions.py\", line 74, in _expect_impl\n    raise AssertionError(\nAssertionError: Locator expected to have text 'View In Cart'\nActual value: <element(s) not found> \nCall log:\nLocatorAssertions.to_have_text with timeout 5000ms\n  - waiting for locator(\"//aside//button[@data-testid='add-to-cart-cta-button']\")\n\n", "record": {"elapsed": {"repr": "0:00:34.054521", "seconds": 34.054521}, "exception": {"type": "AssertionError", "value": "Locator expected to have text 'View In Cart'\nActual value: <element(s) not found> \nCall log:\nLocatorAssertions.to_have_text with timeout 5000ms\n  - waiting for locator(\"//aside//button[@data-testid='add-to-cart-cta-button']\")\n", "traceback": true}, "extra": {}, "file": {"name": "claim.py", "path": "/home/runner/work/Epic-Get/Epic-Get/epic/src/claim.py"}, "function": "run", "level": {"icon": "‚ùå", "name": "ERROR", "no": 40}, "line": 158, "message": "An error has been caught in function 'run', process 'MainProcess' (3792), thread 'MainThread' (140026534710144):", "module": "claim", "name": "__main__", "process": {"id": 3792, "name": "MainProcess"}, "thread": {"id": 140026534710144, "name": "MainThread"}, "time": {"repr": "2024-10-11 07:32:02.416152+08:00", "timestamp": 1728603122.416152}}}
